server:
  port: 7070

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/chemical?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
#    password: XUE_ke_274
    password: 1234
    driverClassName: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: XUEKE274
    password: admin

mybatis-plus:
  mapperLocations: classpath:mapper/*.xml
logging:
  config: classpath:config/logback.xml

